#if !defined(NCMPCPP_SCREEN_DEFS_H)
#define NCMPCPP_SCREEN_DEFS_H

#include "config.h"

#define NCM_SCREEN_FLAG_NONE 0
#define NCM_SCREEN_FLAG_STARTUP 1

#define NCM_SCREEN_TYPE_BROWSER_ENTRY(X) \
    X(NCM_SCREEN_TYPE_BROWSER, NC_SCREEN_TYPE_BROWSER, 1, browser, \
      NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_HELP_ENTRY(X) \
    X(NCM_SCREEN_TYPE_HELP, NC_SCREEN_TYPE_HELP, 2, help, \
      NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_LASTFM_ENTRY(X) \
    X(NCM_SCREEN_TYPE_LASTFM, NC_SCREEN_TYPE_LASTFM, 3, last_fm, \
      NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_LYRICS_ENTRY(X) \
    X(NCM_SCREEN_TYPE_LYRICS, NC_SCREEN_TYPE_LYRICS, 4, lyrics, \
      NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_MEDIA_LIBRARY_ENTRY(X) \
    X(NCM_SCREEN_TYPE_MEDIA_LIBRARY, NC_SCREEN_TYPE_MEDIA_LIBRARY, 5, \
      media_library, NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_OUTPUTS_ENTRY(X) \
    X(NCM_SCREEN_TYPE_OUTPUTS, NC_SCREEN_TYPE_OUTPUTS, 6, outputs, \
      NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_PLAYLIST_ENTRY(X) \
    X(NCM_SCREEN_TYPE_PLAYLIST, NC_SCREEN_TYPE_PLAYLIST, 7, playlist, \
      NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_PLAYLIST_EDITOR_ENTRY(X) \
    X(NCM_SCREEN_TYPE_PLAYLIST_EDITOR, NC_SCREEN_TYPE_PLAYLIST_EDITOR, \
      8, playlist_editor, NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_SEARCH_ENGINE_ENTRY(X) \
    X(NCM_SCREEN_TYPE_SEARCH_ENGINE, NC_SCREEN_TYPE_SEARCH_ENGINE, \
      9, search_engine, NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_SELECTED_ITEMS_ADDER_ENTRY(X) \
    X(NCM_SCREEN_TYPE_SELECTED_ITEMS_ADDER, \
      NC_SCREEN_TYPE_SELECTED_ITEMS_ADDER, 10, selected_items_adder, \
      NCM_SCREEN_FLAG_NONE)
#define NCM_SCREEN_TYPE_SERVER_INFO_ENTRY(X) \
    X(NCM_SCREEN_TYPE_SERVER_INFO, NC_SCREEN_TYPE_SERVER_INFO, 11, \
      server_info, NCM_SCREEN_FLAG_NONE)
#define NCM_SCREEN_TYPE_SONG_INFO_ENTRY(X) \
    X(NCM_SCREEN_TYPE_SONG_INFO, NC_SCREEN_TYPE_SONG_INFO, 12, \
      song_info, NCM_SCREEN_FLAG_NONE)
#define NCM_SCREEN_TYPE_SORT_PLAYLIST_DIALOG_ENTRY(X) \
    X(NCM_SCREEN_TYPE_SORT_PLAYLIST_DIALOG, \
      NC_SCREEN_TYPE_SORT_PLAYLIST_DIALOG, 13, sort_playlist_dialog, \
      NCM_SCREEN_FLAG_NONE)
#define NCM_SCREEN_TYPE_TAG_EDITOR_ENTRY(X) \
    X(NCM_SCREEN_TYPE_TAG_EDITOR, NC_SCREEN_TYPE_TAG_EDITOR, 14, \
      tag_editor, NCM_SCREEN_FLAG_STARTUP)
#define NCM_SCREEN_TYPE_TINY_TAG_EDITOR_ENTRY(X) \
    X(NCM_SCREEN_TYPE_TINY_TAG_EDITOR, NC_SCREEN_TYPE_TINY_TAG_EDITOR, \
      15, tiny_tag_editor, NCM_SCREEN_FLAG_NONE)
#define NCM_SCREEN_TYPE_VISUALIZER_ENTRY(X) \
    X(NCM_SCREEN_TYPE_VISUALIZER, NC_SCREEN_TYPE_VISUALIZER, 16, \
      visualizer, NCM_SCREEN_FLAG_STARTUP)

#define NCM_SCREEN_ALL_TYPES_BEFORE_UNKNOWN(X) \
    NCM_SCREEN_TYPE_BROWSER_ENTRY(X) \
    NCM_SCREEN_TYPE_HELP_ENTRY(X) \
    NCM_SCREEN_TYPE_LASTFM_ENTRY(X) \
    NCM_SCREEN_TYPE_LYRICS_ENTRY(X) \
    NCM_SCREEN_TYPE_MEDIA_LIBRARY_ENTRY(X) \
    NCM_SCREEN_TYPE_OUTPUTS_ENTRY(X) \
    NCM_SCREEN_TYPE_PLAYLIST_ENTRY(X) \
    NCM_SCREEN_TYPE_PLAYLIST_EDITOR_ENTRY(X) \
    NCM_SCREEN_TYPE_SEARCH_ENGINE_ENTRY(X) \
    NCM_SCREEN_TYPE_SELECTED_ITEMS_ADDER_ENTRY(X) \
    NCM_SCREEN_TYPE_SERVER_INFO_ENTRY(X) \
    NCM_SCREEN_TYPE_SONG_INFO_ENTRY(X) \
    NCM_SCREEN_TYPE_SORT_PLAYLIST_DIALOG_ENTRY(X) \
    NCM_SCREEN_TYPE_TAG_EDITOR_ENTRY(X) \
    NCM_SCREEN_TYPE_TINY_TAG_EDITOR_ENTRY(X)

#define NCM_SCREEN_ALL_TYPES_AFTER_UNKNOWN(X) \
    NCM_SCREEN_TYPE_VISUALIZER_ENTRY(X)

#define NCM_SCREEN_ALL_TYPES(X) \
    NCM_SCREEN_ALL_TYPES_BEFORE_UNKNOWN(X) \
    NCM_SCREEN_ALL_TYPES_AFTER_UNKNOWN(X)

#if defined(ENABLE_OUTPUTS)
  #define NCM_SCREEN_ENABLED_OUTPUTS_TYPES(X) \
      NCM_SCREEN_TYPE_OUTPUTS_ENTRY(X)
#else
  #define NCM_SCREEN_ENABLED_OUTPUTS_TYPES(X)
#endif

#if defined(HAVE_TAGLIB_H)
  #define NCM_SCREEN_ENABLED_TAG_EDITOR_TYPES(X) \
      NCM_SCREEN_TYPE_TAG_EDITOR_ENTRY(X) \
      NCM_SCREEN_TYPE_TINY_TAG_EDITOR_ENTRY(X)
#else
  #define NCM_SCREEN_ENABLED_TAG_EDITOR_TYPES(X)
#endif

#if defined(ENABLE_VISUALIZER)
  #define NCM_SCREEN_ENABLED_VISUALIZER_TYPES(X) \
      NCM_SCREEN_TYPE_VISUALIZER_ENTRY(X)
#else
  #define NCM_SCREEN_ENABLED_VISUALIZER_TYPES(X)
#endif

#define NCM_SCREEN_TYPES_BEFORE_UNKNOWN(X) \
    NCM_SCREEN_TYPE_BROWSER_ENTRY(X) \
    NCM_SCREEN_TYPE_HELP_ENTRY(X) \
    NCM_SCREEN_TYPE_LASTFM_ENTRY(X) \
    NCM_SCREEN_TYPE_LYRICS_ENTRY(X) \
    NCM_SCREEN_TYPE_MEDIA_LIBRARY_ENTRY(X) \
    NCM_SCREEN_ENABLED_OUTPUTS_TYPES(X) \
    NCM_SCREEN_TYPE_PLAYLIST_ENTRY(X) \
    NCM_SCREEN_TYPE_PLAYLIST_EDITOR_ENTRY(X) \
    NCM_SCREEN_TYPE_SEARCH_ENGINE_ENTRY(X) \
    NCM_SCREEN_TYPE_SELECTED_ITEMS_ADDER_ENTRY(X) \
    NCM_SCREEN_TYPE_SERVER_INFO_ENTRY(X) \
    NCM_SCREEN_TYPE_SONG_INFO_ENTRY(X) \
    NCM_SCREEN_TYPE_SORT_PLAYLIST_DIALOG_ENTRY(X) \
    NCM_SCREEN_ENABLED_TAG_EDITOR_TYPES(X)

#define NCM_SCREEN_TYPES_AFTER_UNKNOWN(X) \
    NCM_SCREEN_ENABLED_VISUALIZER_TYPES(X)

#define NCM_SCREEN_TYPES(X) \
    NCM_SCREEN_TYPES_BEFORE_UNKNOWN(X) \
    NCM_SCREEN_TYPES_AFTER_UNKNOWN(X)

#define NCM_SCREEN_NATIVE_TYPE_ENUM_FIELD( \
    screen_type, native_type, native_value, alias, flags \
) \
    native_type = native_value,

#define NCM_SCREEN_TYPE_XENUM_FIELD( \
    screen_type, native_type, native_value, alias, flags \
) \
    X(screen_type, alias)

#define NCM_SCREEN_TYPE_ENUM_FIELDS \
    NCM_SCREEN_TYPES_BEFORE_UNKNOWN(NCM_SCREEN_TYPE_XENUM_FIELD) \
    X(NCM_SCREEN_TYPE_UNKNOWN, unknown) \
    NCM_SCREEN_TYPES_AFTER_UNKNOWN(NCM_SCREEN_TYPE_XENUM_FIELD)

#endif /* NCMPCPP_SCREEN_DEFS_H */
