#if !defined(NCMPCPP_TESTS_MPD_TAG_H)
#define NCMPCPP_TESTS_MPD_TAG_H

enum mpd_tag_type {
    MPD_TAG_UNKNOWN = -1,
    MPD_TAG_ARTIST,
    MPD_TAG_ALBUM,
    MPD_TAG_ALBUM_ARTIST,
    MPD_TAG_TITLE,
    MPD_TAG_TRACK,
    MPD_TAG_NAME,
    MPD_TAG_GENRE,
    MPD_TAG_DATE,
    MPD_TAG_COMPOSER,
    MPD_TAG_PERFORMER,
    MPD_TAG_COMMENT,
    MPD_TAG_DISC,
};

#endif /* NCMPCPP_TESTS_MPD_TAG_H */
