#if !defined(NCMPCPP_TESTS_MPD_VERSION_H)
#define NCMPCPP_TESTS_MPD_VERSION_H

#define LIBMPDCLIENT_MAJOR_VERSION 2
#define LIBMPDCLIENT_MINOR_VERSION 25
#define LIBMPDCLIENT_PATCH_VERSION 0

#endif /* NCMPCPP_TESTS_MPD_VERSION_H */
