#ifndef NCMPCPP_CONFIG_H
#define NCMPCPP_CONFIG_H

#define ENABLE_OUTPUTS 1
#define ENABLE_VISUALIZER 1
#define HAVE_CURL_CURL_H 1
#define HAVE_CURSES_H 1
#define HAVE_FFTW3_H 1
#define HAVE_LIBNCURSESW 1
#define HAVE_LIBREADLINE 1
#define HAVE_MPD_CLIENT_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_READLINE_HISTORY 1
#define HAVE_READLINE_HISTORY_H 1
#define HAVE_READLINE_READLINE_H 1
#define HAVE_TAGLIB_FILE_NEW 1
#define HAVE_TAGLIB_FILE_SAVE 1
#define HAVE_TAGLIB_H 1
#define HAVE_TAGLIB_PROPERTY_GET 1
#define HAVE_TAGLIB_PROPERTY_SET 1
#define HAVE_TAGLIB_PROPERTY_SET_APPEND 1
#define PACKAGE "ncmpcpp"
#define PACKAGE_NAME "ncmpcpp"
#define PACKAGE_STRING "ncmpcpp 0.10.2_dev"
#define PACKAGE_TARNAME "ncmpcpp"
#define PACKAGE_VERSION "0.10.2_dev"
#define VERSION "0.10.2_dev"

#endif
